name: 📖 Documentation IAM Startpack

on:
  push:
    branches: [feature/doc]
    paths:
      - "doc/**"

jobs:
  build:
    name: 🛠️ Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: |
          cd doc
          npm ci

      - name: Build the documentation
        run: |
          cd doc
          npm run build

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: ./doc/build

  deploy:
    name: 🚢 Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: doc
          path: ./doc/build

      - name: Deploy the documentation
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude="/dist"
          path: ${{ secrets.PROD_REMOTE_SOURCE_PATH }}/doc/build
          remote_path: ${{ secrets.PROD_REMOTE_ROOT_PATH }}
          remote_host: ${{ secrets.PROD_REMOTE_HOST }}
          remote_port: ${{ secrets.PROD_REMOTE_PORT }}
          remote_user: ${{ secrets.PROD_REMOTE_USER }}
          remote_key: ${{ secrets.PROD_SSH_REMOTE_KEY }}
          remote_key_pass: ${{ secrets.PROD_SSH_REMOTE_KEY_PASS }}
