name: Deploy IAM Starterpack

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: dev 

    steps:
      - name: Pull latest changes
        run: |
          cd /var/www/iam-starterpack
          sudo git fetch --tags  # Ambil semua tag terbaru
          sudo git checkout $GITHUB_REF  # Checkout ke tag release baru
          sudo git pull origin $GITHUB_REF  # Pull perubahan dari tag

      - name: Install dependencies
        run: |
          cd /var/www/iam-starterpack
          sudo npm install
          sudo npm run build

      - name: Install dependencies for docs
        run: |
          cd /var/www/iam-starterpack/doc
          sudo npm install
          sudo npm run build 

      - name: Restart PM2 service
        run: sudo pm2 restart iam-starterpack
