name: Deploy IAM Starterpack

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch yang digunakan

jobs:
  deploy:
    runs-on: dev  # Menggunakan runner di server

    steps:
      - name: Pull latest changes
        run: |
          cd /var/www/iam-starterpack
          sudo git pull origin main

      - name: Install dependencies
        run: |
          cd /var/www/iam-starterpack
          sudo npm install
          sudo npm run build

      - name: Install dependencies docs
        run: |
          cd /var/www/iam-starterpack/doc
          sudo npm install
          sudo npm run build 

      - name: Restart PM2 service
        run: sudo pm2 restart iam-starterpack
